[package]
distribution = "2201.7.0"
org = "ballerinax"
name = "mongodb"
version = "@project.version@"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["IT Operations/Databases", "Cost/Freemium"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-mongodb"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
path = "../native/build/libs/mongodb-native-@project.version@.jar"
groupId = "org.ballerinalang"
artifactId = "mongodb-native"
version = "@project.version@"

[[platform.java17.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-core"
version = "@jackson.version@"
path = "./lib/jackson-core-@jackson.version@.jar"

[[platform.java11.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-annotations"
version = "@jackson.version@"
path = "./lib/jackson-annotations-@jackson.version@.jar"

[[platform.java11.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-databind"
version = "@jackson.version@"
path = "./lib/jackson-databind-@jackson.version@.jar"
