[package]
distribution = "2201.7.0"
org = "ballerinax"
name = "mongodb"
version = "@toml.version@"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["IT Operations/Databases", "Cost/Freemium"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-mongodb"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "io.ballerina.lib"
artifactId = "mongodb-native"
version = "@project.version@"
path = "../native/build/libs/mongodb-native-@project.version@.jar"

[[platform.java17.dependency]]
groupId = "org.mongodb"
artifactId = "mongodb-driver-sync"
version = "@mongodb.driver.version@"
path = "./lib/mongodb-driver-sync-@mongodb.driver.version@.jar"

[[platform.java17.dependency]]
groupId = "org.mongodb"
artifactId = "mongodb-driver-core"
version = "@mongodb.driver.version@"
path = "./lib/mongodb-driver-core-@mongodb.driver.version@.jar"

[[platform.java17.dependency]]
groupId = "org.mongodb"
artifactId = "bson"
version = "@mongodb.driver.version@"
path = "./lib/bson-@mongodb.driver.version@.jar"
