[package]
distribution = "2201.7.0"
org = "ballerinax"
name = "mongodb"
version = "5.0.0-SNAPSHOT"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["IT Operations/Databases", "Cost/Freemium"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-mongodb"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
path = "../native/build/libs/mongodb-native-5.0.0-SNAPSHOT.jar"
groupId = "org.ballerinalang"
artifactId = "mongodb-native"
version = "5.0.0-SNAPSHOT"

[[platform.java17.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-core"
version = "2.15.2"
path = "./lib/jackson-core-2.15.2.jar"

[[platform.java11.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-annotations"
version = "2.15.2"
path = "./lib/jackson-annotations-2.15.2.jar"

[[platform.java11.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-databind"
version = "2.15.2"
path = "./lib/jackson-databind-2.15.2.jar"
