[package]
org = "ballerinax"
name = "mongodb"
version = "2.0.3"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["MongoDB", "NoSQL"]
repository = "https://github.com/ballerina-platform/module-ballerinax-mongodb"

[[platform.java11.dependency]]
path = "../mongo-utils/target/mongo-utils-2.0.3.jar"
groupId = "org.wso2.ei"
artifactId = "mongo-utils"
version = "2.0.3"

[[platform.java11.repository]]
id = "github.releases"
url = "https://maven.pkg.github.com/ballerina-platform/ballerina-lang"
username = "@encrypted:{k9qx7LwfIyse3ZUn2NeHSIKORnHenSbyDbey82Jp3oU/8iDiY+ALCJVUwWKiAKhU}"
password = "@encrypted:{/6nOc0PDC9jwvSwTDsF1Ha1/+bmkRgK2ius9K4qgZMf7spZe9PvxBF/6bXO900j3KUmYxtuiiTlwNs16lv5W7A==}"
