[project]
org-name= "wso2"
version= "0.9.0"

[dependencies]

[platform]
target = "java8"

    [[platform.libraries]]
    module = "mongodb"
    path = "../mongo-utils/target/mongo-utils-0.9.0.jar"
    artafactId = "mongo-utils"
    version = "0.9.0"
    groupId = "org.wso2.ei"
