[package]
org = "ballerinax"
name = "mongodb"
version = "3.0.0"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["IT Operations/Databases", "Cost/Freemium"]
repository = "https://github.com/ballerina-platform/module-ballerinax-mongodb"

[[platform.java11.dependency]]
path = "../mongodb-native/build/libs/mongodb-native-3.0.0-all.jar"
groupId = "org.ballerinalang"
artifactId = "mongodb-native"
version = "3.0.0"
