[project]
org-name= "wso2"
version= "0.9.2"

[dependencies]

[platform]
target = "java8"

[[platform.libraries]]
module = "mongodb"
path = "../mongo-utils/target/mongo-utils-0.9.2.jar"
artafactId = "mongo-utils"
version = "0.9.2"
groupId = "org.wso2.ei"
