[[dependency]]
org = "ballerina"
name = "crypto"
version = "2.0.0"

[[dependency]]
org = "ballerina"
name = "log"
version = "2.0.0"

[[dependency]]
org = "ballerina"
name = "file"
version = "1.0.0"

[[dependency]]
org = "ballerina"
name = "os"
version = "1.0.0"
