name: CI

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        services:
          mongodb:
            image: mongo:4.2.0
            env:
              # Following credentials are only used during testing in docker container
              MONGO_INITDB_ROOT_USERNAME: admin
              MONGO_INITDB_ROOT_PASSWORD: admin
          mongodb-ssl:
            image: rzhilkibaev/mongo-x509-auth-ssl:latest

        steps:
            - uses: actions/checkout@v3
            - name: Set up JDK 11
              uses: actions/setup-java@v3
              with:
                distribution: 'zulu'
                java-version: 11 
            - name: Grant execute permission for gradlew
              run: chmod +x gradlew

            - name: Build with Gradle
              env:
                packageUser: ${{ secrets.BALLERINA_BOT_USERNAME }}
                packagePAT: ${{ secrets.BALLERINA_BOT_TOKEN }}
                JAVA_OPTS: -DBALLERINA_DEV_COMPILE_BALLERINA_ORG=true
              run: |
                ./gradlew build
     
            - name: Ballerina Build
              uses: ballerina-platform/ballerina-action/@nightly
              with:
                args:
                  pack mongodb
              env:
                JAVA_HOME: /usr/lib/jvm/default-jvm
                JAVA_OPTS: -DBALLERINA_DEV_COMPILE_BALLERINA_ORG=true

            - name: SSL Tests
              uses: ballerina-platform/ballerina-action/@nightly
              with:
                args:
                  test --groups mongodb-ssl --code-coverage
              env:
                JAVA_HOME: /usr/lib/jvm/default-jvm
                # Following credentials are only used during testing in docker container
                WORKING_DIR: ./mongodb
                MONGODB_HOST: mongodb-ssl
                MONGODB_USER: C=US,ST=CA,L=San Francisco,O=Jaspersoft,OU=JSDev,CN=admin
                
            - name: MongoDB Tests
              uses: ballerina-platform/ballerina-action/@nightly
              with:
                args:
                  test --groups mongodb --code-coverage mongodb
              env:
                JAVA_HOME: /usr/lib/jvm/default-jvm
                # Following credentials are only used during testing in docker container
                MONGODB_HOST: mongodb
                MONGODB_USER: admin
                MONGODB_PASSWORD: admin
            

            # Read the ballerina test results
            - name: Read Ballerina Test Results
              id: test_results
              run: |
                content=`cat ./mongodb/target/report/test_results.json`                
                content="${content//'%'/'%25'}"
                content="${content//$'\n'/'%0A'}"
                content="${content//$'\r'/'%0D'}"
                echo "::set-output name=testResultsJson::$content"

            # Print the code coverage information
            - name: Code Coverage
              run: |
                echo "Covered Code Lines : ${{fromJson(steps.test_results.outputs.testResultsJson).coveredLines}}"
                echo "Total Code Lines : $(expr ${{fromJson(steps.test_results.outputs.testResultsJson).missedLines}} + ${{fromJson(steps.test_results.outputs.testResultsJson).coveredLines}})"
                echo "Code Coverage Percentage : ${{fromJson(steps.test_results.outputs.testResultsJson).coveragePercentage}}"
